# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbc6ede642913b78b586bfbaf21de5f8c79102c239d9784831ce52ea14373efa4d3253729bd69a5b503d3881e2be5d6385d2a65979fcc2a76543e45d5bbc41e8

test:
  secret_key_base: 0c818b3b5809854699096034f4e266f7b26c6bb10427a1b3b3da6dbc1a483e2c26bd0587928ec78a751fa5d8093169ee470ac6cf546d8c62adac1a66dab5d3b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
